In [1]:
import numpy as np

In [2]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    result = 0
    for i in range(u.shape[0]):
        result = result + u[i] * v[i]

    return result

In [3]:
u = np.array([1,2,3,4,5])
u

array([1, 2, 3, 4, 5])

In [4]:
v = np.array([1,2,1,3,0])
v

array([1, 2, 1, 3, 0])

In [5]:
vector_vector_multiplication(u,v)

20

In [6]:
u.dot(v)

20

In [7]:
v.dot(u)

20

In [8]:
U = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [0,4,6,3]
])

In [10]:
U.shape

(3, 4)

In [15]:
v[:4]

array([1, 2, 1, 3])

In [31]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    result = np.zeros(U.shape[0])     
    for i in range(U.shape[0]):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [32]:
matrix_vector_multiplication(U, v[:4])

array([20., 48., 23.])

In [34]:
U.dot(v[:4])

array([20, 48, 23])

In [38]:
U

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 4, 6, 3]])

In [45]:
V = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
])

In [46]:
V.shape, U.shape

((4, 4), (3, 4))

In [49]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    rows = U.shape[0] 
    cols = V.shape[1]
    result = np.zeros((rows, cols))
    
    for i in range(cols):
        result[:, i] = matrix_vector_multiplication(U, V[:,i])

    return result

In [50]:
matrix_matrix_multiplication(U, V)

array([[ 10.,  20.,  30.,  40.],
       [ 26.,  52.,  78., 104.],
       [ 13.,  26.,  39.,  52.]])

In [52]:
U.dot(V)

array([[ 10,  20,  30,  40],
       [ 26,  52,  78, 104],
       [ 13,  26,  39,  52]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.linalg.inv(np.array([
    [2, 3, 4],
    [6, 7, 8],
    [4, 6, 3]
))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given