# Introto Numpy

In [3]:
import numpy as np

### 1 Dimensional array

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a[2]

3

In [15]:
a[2] = 20
a[2]

20

In [19]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [26]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional Arrays

In [31]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
n = np.array([
    [1,2,1,4],
    [5,2,2,2],
    [3,1,3,9]
])


print(n[0][1])
n[0,1] 

2


2

In [54]:
n[0] = [0,0,0,0]
n

array([[0, 0, 0, 0],
       [5, 2, 2, 2],
       [3, 1, 3, 9]])

In [55]:
n[:, 2]

array([0, 2, 3])

In [56]:
n[2, :]

array([3, 1, 3, 9])

## Random generated arrays

In [77]:
np.random.rand(5,2) #standard distribution

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [78]:
np.random.randn(5,2) #normal distribution

array([[-0.74787095,  0.00902525],
       [-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905],
       [-0.33882197, -0.23618403],
       [-0.63765501, -1.18761229]])

In [79]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [101]:
# np.random.seed(2)
np.random.randint(5,10,5)

array([7, 5, 9, 9, 7])

## Element wise operator

In [102]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [103]:
a + 1

array([1, 2, 3, 4, 5])

In [104]:
(a * 2) / 3

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667])

In [105]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [109]:
b = (a ** 2) + 0.001
b

array([1.0000e-03, 1.0010e+00, 4.0010e+00, 9.0010e+00, 1.6001e+01])

In [110]:
a + b

array([1.0000e-03, 2.0010e+00, 6.0010e+00, 1.2001e+01, 2.0001e+01])

In [112]:
a / b

array([0.        , 0.999001  , 0.49987503, 0.3332963 , 0.24998438])

## Comparision operations

In [113]:
a >= 2

array([False, False,  True,  True,  True])

In [114]:
a > b

array([False, False, False, False, False])

In [115]:
a[a > b]

array([], dtype=int64)

In [116]:
a[a < b]

array([0, 1, 2, 3, 4])

## Sumarisation 

In [117]:
a.min()

0

In [118]:
b.max()

16.001

In [119]:
b.std()

5.89915248150105